version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - NODE_ENV=production
      - DB_HOST=seru-be-test-postgres-1
      - DB_USER=postgres
      - DB_PASS=admin
      - DB_NAME=seru_car
      - DB_PORT=5432
      - PORT=8000
    depends_on:
      - postgres
    command: npm run db:setup:run

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=seru_car
      - PGPORT=5432
    ports:
      - "5432:5432"
    expose:
      - 5432
    

